######################################################################
# Automatically generated by qmake (2.01a) ter fev 23 16:40:33 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += QT BRISA
CONFIG += qt qxt
QT += core network xml
BRISA += upnp utils core
QXT += core web

# Input
HEADERS += controlpoint.h
SOURCES += controlpoint.cpp main.cpp
