######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 21 10:33:21 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += qxt

QXT += web

# Input
SOURCES += main.cpp
