BRisa Qt: BrisaUpnp::BrisaSSDPClient Class Reference
BrisaUpnp::BrisaSSDPClient Class Reference
SSDP stack implementantion for UPnP control points.
#include <BrisaUpnp/BrisaSSDPClient>
Public Slots
void start ()
Connects to the MultiCast group and starts the client.
void stop ()
Stops the client.
bool isRunning () const
Checks if the client is running.
Signals
void newDeviceEvent (const QString &usn, const QString &location, const QString &st, const QString &ext, const QString &server, const QString &cacheControl)
This signal is emitted when the client receives a "ssdp:alive" message from a device joining the network.
void removedDeviceEvent (const QString &usn)
This signal is emitted when the client receives a "ssdp:byebye" message from a device leaving the network.
Public Member Functions
BrisaSSDPClient (QObject *parent=0)
Constructs a BrisaSSCPClient with the given parent.
~BrisaSSDPClient ()
Destroys the client.
Detailed Description
SSDP stack implementantion for UPnP control points.
Create a new BrisaSSCPClient and call "start()" to connect to the multicast group and start listening to ssdp notification messages.
When BrisaSSDPClient receives a notification message it emits "newDeviceEvent()" in case of "ssdp:alive" and "removedDeviceEvent" in case of "ssdp:byebye". Other ssdp messages will be ignored.
Constructor & Destructor Documentation
BrisaSSDPClient::BrisaSSDPClient (QObject * parent = 0)
Constructs a BrisaSSCPClient with the given parent.
BrisaSSDPClient::~BrisaSSDPClient ()
Destroys the client.
Stops the client if it's running.
Member Function Documentation
bool BrisaSSDPClient::isRunning () const [slot]
Checks if the client is running.
Returns:
true if is running
Referenced by start(), stop(), and ~BrisaSSDPClient().
void BrisaUpnp::BrisaSSDPClient::newDeviceEvent (const QString & usn, const QString & location, const QString & st, const QString & ext, const QString & server, const QString & cacheControl) [signal]
This signal is emitted when the client receives a "ssdp:alive" message from a device joining the network.
See also:
removedDeviceEvent()
void BrisaUpnp::BrisaSSDPClient::removedDeviceEvent (const QString & usn) [signal]
This signal is emitted when the client receives a "ssdp:byebye" message from a device leaving the network.
See also:
newDeviceEvent()
void BrisaSSDPClient::start () [slot]
Connects to the MultiCast group and starts the client.
See also:
isRunning(), stop()
Referenced by BrisaUpnp::BrisaControlPoint::start().
void BrisaSSDPClient::stop () [slot]
Stops the client.
See also:
isRunning(), start()
Referenced by BrisaUpnp::BrisaControlPoint::stop(), and ~BrisaSSDPClient().
The documentation for this class was generated from the following files:
src/upnp/ssdp/brisassdpclient.h
src/upnp/ssdp/brisassdpclient.cpp