BRisa Qt: BrisaUpnp::BrisaAction Class Reference
BrisaUpnp::BrisaAction Class Reference
Template method class that represents each service's action.
#include <BrisaUpnp/BrisaAction>
Public Member Functions
BrisaAction (QString name="", BrisaService *service=0, QObject *parent=0)
Constructs an action with given name, parent and service that it is related to.
BrisaAction (const BrisaAction &action)
Constructs a new action based on action.
virtual ~BrisaAction ()
Destroys the action.
void setName (QString name)
Sets a new name to the action.
QString getName () const
Returns the action's name.
void setService (BrisaService *service)
Sets a new service for this action.
BrisaService * getService () const
Returns the service that this action is related to.
BrisaStateVariable * getStateVariable (const QString &name) const
Returns the related service's state variable with the given name.
QList< BrisaArgument * > getArgumentList () const
Returns this action's list of arguments.
void addArgument (QString name="", QString direction="", QString relatedStateVariable="")
Adds an argument with given name, direction and relatedStateVariable to this action's list of arguments.
void addArgument (BrisaArgument *argumentA)
Adds given argument to this action's list of arguments.
void addArguments (const QList< BrisaArgument * > argumentA)
Adds given list of arguments to this action's list of arguments.
void clearArgumentList ()
Clears this action's argument list.
bool call (const QMap< QString, QString > &inArguments, QMap< QString, QString > &outArguments)
Validates inArguments, outArguments and runs the action.
Protected Member Functions
virtual QMap< QString, QString > run (const QMap< QString, QString > &inArguments)
The actual action.
Detailed Description
Template method class that represents each service's action.
Create a class derived from BrisaAction and reimplement the method run(). That method is the one which is called when this action is invoked and defines the action's behavior.
The method run() receives a QMap<QString, QString> with the input arguments. They are organized as key -- the argument name -- and value -- the argument value. It has to return a QMap<QString, QString> with the output arguments organized the same way.
If any of the returned output arguments is not defined in the service description file, BrisaAction will show an error message at the debug output stream and send an error message to the control point.
Constructor & Destructor Documentation
BrisaAction::BrisaAction (QString name = "", BrisaService * service = 0, QObject * parent = 0)
Constructs an action with given name, parent and service that it is related to.
BrisaAction::BrisaAction (const BrisaAction & action)
Constructs a new action based on action.
BrisaAction::~BrisaAction () [virtual]
Destroys the action.
It has to be overridden for properly destroying the derived actions when necessary.
Member Function Documentation
void BrisaAction::addArgument (BrisaArgument * argumentA)
Adds given argument to this action's list of arguments.
void BrisaAction::addArgument (QString name = "", QString direction = "", QString relatedStateVariable = "")
Adds an argument with given name, direction and relatedStateVariable to this action's list of arguments.
Referenced by addArguments(), and BrisaUpnp::BrisaServiceXMLHandler::endElement().
void BrisaAction::addArguments (const QList< BrisaArgument * > argumentA)
Adds given list of arguments to this action's list of arguments.
Referenced by BrisaUpnp::BrisaServiceXMLHandler::endElement().
bool BrisaAction::call (const QMap< QString, QString > & inArguments, QMap< QString, QString > & outArguments)
Validates inArguments, outArguments and runs the action.
outArguments is an output parameter. This method returns true in case of successful running of the action, else returns false.
void BrisaAction::clearArgumentList ()
Clears this action's argument list.
Referenced by BrisaUpnp::BrisaServiceXMLHandler::endElement().
QList< BrisaArgument * > BrisaAction::getArgumentList () const
Returns this action's list of arguments.
Referenced by BrisaAction(), and BrisaUpnp::BrisaServiceXMLHandler::endElement().
QString BrisaAction::getName () const
Returns the action's name.
Referenced by BrisaUpnp::BrisaAbstractService::addAction(), call(), BrisaUpnp::BrisaServiceXMLHandler::endElement(), and getStateVariable().
BrisaService * BrisaAction::getService () const
Returns the service that this action is related to.
Referenced by getStateVariable().
BrisaStateVariable * BrisaAction::getStateVariable (const QString & name) const
Returns the related service's state variable with the given name.
If it cannot find its related service or the state variable, then it returns a null pointer.
QMap< QString, QString > BrisaAction::run (const QMap< QString, QString > & inArguments) [protected, virtual]
The actual action.
This method must be reimplemented for each user's action. It receives inArguments as input arguments and must return the right output arguments as described in the service's description file.
Referenced by call().
void BrisaAction::setName (QString name)
Sets a new name to the action.
Referenced by BrisaUpnp::BrisaServiceXMLHandler::characters().
void BrisaAction::setService (BrisaService * service)
Sets a new service for this action.
The documentation for this class was generated from the following files:
src/upnp/brisaaction.h
src/upnp/brisaaction.cpp