BRisa Qt: BrisaUpnp::BrisaControlPoint Class Reference
BrisaUpnp::BrisaControlPoint Class Reference
Class that implements the control part in UPnP Architecture.
#include <BrisaUpnp/BrisaControlPoint>
Signals
void deviceFound (BrisaControlPointDevice *device)
This signal is emitted when a new device is find in network and all it's attributes are created by the xml reading.
void deviceGone (QString usn)
This signal is emitted when a device leaves the network, that means that the the ssdp client received a "ssdp:byebye" message from the device and, to handle this, the control point emit a deviceGone event with the device's usn as parameter.
Public Member Functions
BrisaControlPoint (QObject *parent=0, QString st="ssdp:all", int mx=5)
Constructor.
~BrisaControlPoint ()
void start ()
Starts the control point, the ssdpClient and the msearch.
void stop ()
Stops the control point, the ssdpClient and the msearch.
bool isRunning ()
Return if the control point is running.
void discover ()
Starts the control point msearch discover.
BrisaEventProxy * getSubscriptionProxy (BrisaControlPointService *service)
Gets an event proxy to subscribe, usubscribe or renew the events from a service.
Detailed Description
Class that implements the control part in UPnP Architecture.
Create a ControlPoint and start(), then discover() devices will be found in network. If you don't want to look for more devices then use stop().
Constructor & Destructor Documentation
BrisaControlPoint::BrisaControlPoint (QObject * parent = 0, QString st = "ssdp:all", int mx = 5)
Constructor.
Parameters:
parent parent
st service type
mx interval
BrisaControlPoint::~BrisaControlPoint ()
Destructor
Member Function Documentation
void BrisaUpnp::BrisaControlPoint::deviceFound (BrisaControlPointDevice * device) [signal]
This signal is emitted when a new device is find in network and all it's attributes are created by the xml reading.
See also:
deviceGone(QString usn)
Referenced by BrisaControlPoint().
void BrisaUpnp::BrisaControlPoint::deviceGone (QString usn) [signal]
This signal is emitted when a device leaves the network, that means that the the ssdp client received a "ssdp:byebye" message from the device and, to handle this, the control point emit a deviceGone event with the device's usn as parameter.
See also:
deviceFound(BrisaControlPointDevice *device)
void BrisaControlPoint::discover ()
Starts the control point msearch discover.
BrisaEventProxy * BrisaControlPoint::getSubscriptionProxy (BrisaControlPointService * service)
Gets an event proxy to subscribe, usubscribe or renew the events from a service.
Parameters:
service empty
bool BrisaControlPoint::isRunning ()
Return if the control point is running.
Returns:
true if the control point is running or false otherwise
See also:
start(), stop()
Referenced by start(), stop(), and ~BrisaControlPoint().
void BrisaControlPoint::start ()
Starts the control point, the ssdpClient and the msearch.
See also:
stop(), isRunning()
void BrisaControlPoint::stop ()
Stops the control point, the ssdpClient and the msearch.
See also:
start(), isRunning()
Referenced by ~BrisaControlPoint().
The documentation for this class was generated from the following files:
src/upnp/controlpoint/brisacontrolpoint.h
src/upnp/controlpoint/brisacontrolpoint.cpp