BRisa Qt: BrisaUpnp::BrisaSSDPServer Class Reference
BrisaUpnp::BrisaSSDPServer Class Reference
SSDP stack implementation for UPnP devices.
#include <BrisaUpnp/BrisaSSDPServer>
Public Slots
bool isRunning ()
Checks if BrisaSSDPServer is running.
void start ()
Joins the multicast group and starts listening for UPnP msearch responses.
void stop ()
Stops the BrisaSSDPServer.
void doNotify (const QString &usn, const QString &location, const QString &st, const QString &server, const QString &cacheControl)
Sends a UPnP notify alive message to the multicast group with the given information.
void doByeBye (const QString &usn, const QString &st)
Sends a UPnP notify byebye message to the multicast group with the given information.
void respondMSearch (const QString &senderIp, quint16 senderPort, const QString &cacheControl, const QString &date, const QString &location, const QString &server, const QString &st, const QString &usn)
Sends a UPnP msearch response message to the given sender IP address and port.
Signals
void msearchRequestReceived (const QString &st, const QString &senderIp, quint16 senderPort)
This signal is emmited when the BrisaSSDPServer receives a valid UPnP msearch request.
Public Member Functions
BrisaSSDPServer (QObject *parent=0)
Constructs a BrisaSSDPServer with the given parent object.
virtual ~BrisaSSDPServer ()
Destroys the Object.
Detailed Description
SSDP stack implementation for UPnP devices.
Call start() to begin listening for MSearch requests from control points. Whenever a new msearch request is parsed by the BrisaSSDPServer, a msearchRequestReceived() signal is emmited containning all of the request information. You can connect this signal to some slot wich calls respondMSearch() and get a synchronous response to msearch requests.
BrisaSSDPServer also implements SSDP notify messages. Call doNotify() or doByeBye() when entering or leaving the multicast group.
Constructor & Destructor Documentation
BrisaSSDPServer::BrisaSSDPServer (QObject * parent = 0)
Constructs a BrisaSSDPServer with the given parent object.
Parameters:
parent parent
BrisaSSDPServer::~BrisaSSDPServer () [virtual]
Destroys the Object.
Stops the server if running.
Member Function Documentation
void BrisaSSDPServer::doByeBye (const QString & usn, const QString & st) [slot]
Sends a UPnP notify byebye message to the multicast group with the given information.
Parameters:
usn empty
st empty
See also:
doNotify()
Referenced by BrisaUpnp::BrisaDevice::doByeBye().
void BrisaSSDPServer::doNotify (const QString & usn, const QString & location, const QString & st, const QString & server, const QString & cacheControl) [slot]
Sends a UPnP notify alive message to the multicast group with the given information.
Parameters:
usn empty
location empty
st empty
server empty
cacheControl empty
See also:
doByeBye()
Referenced by BrisaUpnp::BrisaDevice::doNotify().
bool BrisaSSDPServer::isRunning () [slot]
Checks if BrisaSSDPServer is running.
Returns:
true if is running
Referenced by start(), stop(), and ~BrisaSSDPServer().
void BrisaUpnp::BrisaSSDPServer::msearchRequestReceived (const QString & st, const QString & senderIp, quint16 senderPort) [signal]
This signal is emmited when the BrisaSSDPServer receives a valid UPnP msearch request.
Parameters:
st empty
senderIp empty
senderPort empty
See also:
respondMSearch()
void BrisaSSDPServer::respondMSearch (const QString & senderIp, quint16 senderPort, const QString & cacheControl, const QString & date, const QString & location, const QString & server, const QString & st, const QString & usn) [slot]
Sends a UPnP msearch response message to the given sender IP address and port.
Connect this slot to a proper signal to get synchronous response for msearch requests.
Parameters:
sender Ip empty
senderPort empty
cacheControl empty
date empty
location empty
server empty
st empty
usn empty
See also:
msearchRequestReceived()
Referenced by BrisaUpnp::BrisaDevice::respondMSearch().
void BrisaSSDPServer::start () [slot]
Joins the multicast group and starts listening for UPnP msearch responses.
See also:
stop()
Referenced by BrisaUpnp::BrisaDevice::start().
void BrisaSSDPServer::stop () [slot]
Stops the BrisaSSDPServer.
See also:
start()
Referenced by BrisaUpnp::BrisaDevice::stop(), and ~BrisaSSDPServer().
The documentation for this class was generated from the following files:
src/upnp/ssdp/brisassdpserver.h
src/upnp/ssdp/brisassdpserver.cpp