BRisa Qt: BrisaUpnp::BrisaControlPointDevice Class Reference
BrisaUpnp::BrisaControlPointDevice Class Reference
Class that implements the devices that control point part is going to handle.
#include <BrisaUpnp/BrisaControlPointDevice>
Public Types
enum xmlTags {
Major, Minor, UrlBase, DeviceType,
FriendlyName, Manufacturer, ManufacturerUrl, ModelDescription,
ModelName, ModelNumber, ModelUrl, SerialNumber,
Udn, Upc, PresentationUrl, FileAddress
}
Public Member Functions
BrisaControlPointDevice (QObject *parent=0)
Constructor to BrisaControlPointDevice, when it makes use of this constructor the device's attributes should be set.
BrisaControlPointDevice (QTemporaryFile *xml, QUrl *url, QObject *parent=0)
Constructor for BrisaControlPointDevice that receives a xml file containing the device description, so that the device's attributes can be initialized.
BrisaControlPointDevice (BrisaControlPointDevice &dev, QObject *parent=0)
Constructor for BrisaControlPointDevice that receives another object of the same type and copy it's attributes.
BrisaControlPointDevice (QString deviceType, QString friendlyName="", QString manufacturer="", QString manufacturerURL="", QString modelDescription="", QString modelName="", QString modelNumber="", QString modelURL="", QString serialNumber="", QString UDN="", QString UPC="", QString presentationURL="", QObject *parent=0)
Constructor where all device's attributes are passed as parameter.
~BrisaControlPointDevice ()
Destructor.
QString getAttribute (xmlTags key)
Gets an attribute by key.
void setAttribute (xmlTags key, QString value)
Set a device's attribute.
void addIcon (BrisaIcon *icon)
Add an icon to device's icon list.
void addService (BrisaControlPointService *service)
Add service to device's service list.
void addDevice (BrisaControlPointDevice *device)
Add a device to device's embedded device list.
QList< BrisaIcon * > getIconList ()
Gets device's icon list.
QList
< BrisaControlPointService * > & getServiceList ()
Gets device's service list.
QList< BrisaControlPointDevice * > getEmbeddedDeviceList ()
Gets device's embedded device list.
BrisaControlPointService * getServiceById (QString serviceId)
Gets a service by id.
BrisaControlPointService * getServiceByType (QString serviceType)
Check the device's service list and return the service that has the passed .
void clear ()
Clear device's attributes.
Detailed Description
Class that implements the devices that control point part is going to handle.
Member Enumeration Documentation
enum BrisaUpnp::BrisaControlPointDevice::xmlTags
Enumerator:
Major
Minor
UrlBase
DeviceType
FriendlyName
Manufacturer
ManufacturerUrl
ModelDescription
ModelName
ModelNumber
ModelUrl
SerialNumber
Udn
Upc
PresentationUrl
FileAddress
Constructor & Destructor Documentation
BrisaControlPointDevice::BrisaControlPointDevice (QObject * parent = 0)
Constructor to BrisaControlPointDevice, when it makes use of this constructor the device's attributes should be set.
Parameters:
parent empty
BrisaControlPointDevice::BrisaControlPointDevice (QTemporaryFile * xml, QUrl * url, QObject * parent = 0)
Constructor for BrisaControlPointDevice that receives a xml file containing the device description, so that the device's attributes can be initialized.
Parameters:
xml empty
url empty
parent empty
BrisaControlPointDevice::BrisaControlPointDevice (BrisaControlPointDevice & dev, QObject * parent = 0)
Constructor for BrisaControlPointDevice that receives another object of the same type and copy it's attributes.
BrisaControlPointDevice::BrisaControlPointDevice (QString deviceType, QString friendlyName = "", QString manufacturer = "", QString manufacturerURL = "", QString modelDescription = "", QString modelName = "", QString modelNumber = "", QString modelURL = "", QString serialNumber = "", QString UDN = "", QString UPC = "", QString presentationURL = "", QObject * parent = 0)
Constructor where all device's attributes are passed as parameter.
Parameters:
deviceType empty
friendlyName empty
manufacturer empty
manufacturerURL empty
modelDescription empty
modelName empty
modelNumber empty
modelURL empty
serialNumber empty
UDN empty
UPC empty
presentationURL empty
parent empty
BrisaControlPointDevice::~BrisaControlPointDevice ()
Destructor.
Member Function Documentation
void BrisaControlPointDevice::addDevice (BrisaControlPointDevice * device)
Add a device to device's embedded device list.
Parameters:
device device to add
Referenced by BrisaUpnp::BrisaDeviceXMLHandlerCP::endElement().
void BrisaControlPointDevice::addIcon (BrisaIcon * icon)
Add an icon to device's icon list.
Parameters:
icon icon to add
Referenced by BrisaUpnp::BrisaDeviceXMLHandlerCP::endElement().
void BrisaControlPointDevice::addService (BrisaControlPointService * service)
Add service to device's service list.
Parameters:
service service to add
Referenced by BrisaUpnp::BrisaDeviceXMLHandlerCP::endElement().
void BrisaControlPointDevice::clear ()
Clear device's attributes.
QString BrisaControlPointDevice::getAttribute (xmlTags key)
Gets an attribute by key.
Parameters:
key attribute key
Returns:
attribute value
Referenced by BrisaControlPointDevice(), and BrisaUpnp::BrisaDeviceXMLHandlerCP::endElement().
QList< BrisaControlPointDevice * > BrisaControlPointDevice::getEmbeddedDeviceList ()
Gets device's embedded device list.
Returns:
embedded list
Referenced by BrisaControlPointDevice().
QList< BrisaIcon * > BrisaControlPointDevice::getIconList ()
Gets device's icon list.
Returns:
icon list
Referenced by BrisaControlPointDevice().
BrisaControlPointService * BrisaControlPointDevice::getServiceById (QString serviceId)
Gets a service by id.
Parameters:
serviceId service id
Returns:
service with corresponding id
BrisaControlPointService * BrisaControlPointDevice::getServiceByType (QString serviceType)
Check the device's service list and return the service that has the passed .
Parameters:
serviceType type of the service
Returns:
service with corresponding type
QList< BrisaControlPointService * > & BrisaControlPointDevice::getServiceList ()
Gets device's service list.
Returns:
service list
Referenced by BrisaControlPointDevice().
void BrisaControlPointDevice::setAttribute (xmlTags key, QString value)
Set a device's attribute.
Parameters:
key attribute key
value new attribute value
Referenced by BrisaControlPointDevice(), and BrisaUpnp::BrisaDeviceXMLHandlerCP::characters().
The documentation for this class was generated from the following files:
src/upnp/controlpoint/brisacontrolpointdevice.h
src/upnp/controlpoint/brisacontrolpointdevice.cpp