BRisa Qt: BrisaUpnp::BrisaDevice Class Reference
BrisaUpnp::BrisaDevice Class Reference
UPnP device implementation.
#include <BrisaUpnp/BrisaDevice>
Public Types
enum xmlTags {
Major, Minor, UrlBase, DeviceType,
FriendlyName, Manufacturer, ManufacturerUrl, ModelDescription,
ModelName, ModelNumber, ModelUrl, SerialNumber,
Udn, Upc, PresentationUrl, FileAddress,
Location, Server, IpAddress, Port,
Running
}
Public Slots
void respondMSearch (const QString &st, const QString &senderIp, quint16 senderPort)
Slot connected to the msearchRequestReceived() signal comming from the ssdp module.
Public Member Functions
BrisaDevice (QObject *parent=0)
Creates a BrisaDevice with the given parent QObject.
BrisaDevice (const BrisaDevice &dev)
Copy constructor.
BrisaDevice (const QString &deviceType, QString friendlyName="", const QString &manufacturer="", const QString &manufacturerURL="", const QString &modelDescription="", const QString &modelName="", const QString &modelNumber="", const QString &modelURL="", const QString &serialNumber="", const QString &UDN="", const QString &UPC="", const QString &presentationURL="", QObject *parent=0)
Creates a BrisaDevice with the given device information.
~BrisaDevice ()
Destructor for BrisaDevice.
BrisaDevice & operator= (const BrisaDevice &dev)
Assigns dev to this BrisaDevice and returns a copy.
void setAttribute (xmlTags key, const QString &value)
Attribute setter.
QString getAttribute (xmlTags key) const
Attribute getter.
void addIcon (const QString &mimetype="", const QString &width="", const QString &height="", const QString &depth="", const QString &url="")
Call this method to add a icon to the device.
void addService (const QString &serviceType="", const QString &serviceId="", const QString &SCPDURL="", const QString &controlURL="", const QString &eventSubURL="")
Creates and adds a service to the device with the given information.
void addService (BrisaService *serv)
Overloads addService().
void addEmbeddedDevice (const QString &deviceType="", const QString &friendlyName="", const QString &manufacturer="", const QString &manufacturerURL="", const QString &modelDescription="", const QString &modelName="", const QString &modelNumber="", const QString &modelURL="", const QString &serialNumber="", const QString &UDN="", const QString &UPC="", const QString &presentationURL="")
Creates and adds a embedded device with the given information to the device.
void addEmbeddedDevice (BrisaDevice *newEmbeddedDevice)
Overloads addEmbeddedDevice() Create a new BrisaDevice and call this method to add it as a embedded device to a root device.
QList< BrisaIcon > getIconList () const
Returns the icon list.
QList< BrisaService * > getServiceList () const
Returns the service list.
QList< BrisaDevice * > getEmbeddedDeviceList () const
Returns the embedded device list.
BrisaService * getServiceById (const QString &serviceId)
Getter for BrisaService in the service list.
BrisaService * getServiceByType (const QString &serviceType)
Getter for BrisaService in the service list.
void clear ()
Clears the device information, including services, icons and embedded devices.
void doNotify ()
Sends the ssdp:alive messages for root device, embedded devices and services according to the UPnP 1.0 especification.
void doByeBye ()
Sends the ssdp:byebye messages for root device, embedded devices and services according to the UPnP 1.0 especification.
void start ()
Call this method to join the network and start the device.
void stop ()
Stops the device and leaves the network.
Detailed Description
UPnP device implementation.
BrisaDevice provides a easy and fast way to create UPnP devices. Simply create a new BrisaDevice and call start() to join the network and be visible to available control points.
To add a service to the device, just create a new BrisaService with the chosen actions and events and add it to the device by calling addService(). The service will be automatically added to the device and the appropriate webserver urls paths will be created.
Embedded devices are also supported by BrisaDevice. Create a new BrisaDevice and call addEmbeddedDevice(), the embedded device will be announced when the root device joins the network.
To stop the device and leave the network, simply call the stop() method, ssdp messages will also be sent for any embedded devices.
See also:
BrisaUpnp::BrisaService
Member Enumeration Documentation
enum BrisaUpnp::BrisaDevice::xmlTags
Enumerator:
Major
Minor
UrlBase
DeviceType
FriendlyName
Manufacturer
ManufacturerUrl
ModelDescription
ModelName
ModelNumber
ModelUrl
SerialNumber
Udn
Upc
PresentationUrl
FileAddress
Location
Server
IpAddress
Port
Running
Constructor & Destructor Documentation
BrisaDevice::BrisaDevice (QObject * parent = 0)
Creates a BrisaDevice with the given parent QObject.
Referenced by addEmbeddedDevice().
BrisaDevice::BrisaDevice (const BrisaDevice & dev)
Copy constructor.
BrisaDevice::BrisaDevice (const QString & deviceType, QString friendlyName = "", const QString & manufacturer = "", const QString & manufacturerURL = "", const QString & modelDescription = "", const QString & modelName = "", const QString & modelNumber = "", const QString & modelURL = "", const QString & serialNumber = "", const QString & UDN = "", const QString & UPC = "", const QString & presentationURL = "", QObject * parent = 0)
Creates a BrisaDevice with the given device information.
BrisaDevice::~BrisaDevice ()
Destructor for BrisaDevice.
Stops the device if running.
Member Function Documentation
void BrisaDevice::addEmbeddedDevice (BrisaDevice * newEmbeddedDevice)
Overloads addEmbeddedDevice() Create a new BrisaDevice and call this method to add it as a embedded device to a root device.
We recommend using this method for better object orientation.
void BrisaDevice::addEmbeddedDevice (const QString & deviceType = "", const QString & friendlyName = "", const QString & manufacturer = "", const QString & manufacturerURL = "", const QString & modelDescription = "", const QString & modelName = "", const QString & modelNumber = "", const QString & modelURL = "", const QString & serialNumber = "", const QString & UDN = "", const QString & UPC = "", const QString & presentationURL = "")
Creates and adds a embedded device with the given information to the device.
void BrisaDevice::addIcon (const QString & mimetype = "", const QString & width = "", const QString & height = "", const QString & depth = "", const QString & url = "")
Call this method to add a icon to the device.
void BrisaDevice::addService (BrisaService * serv)
Overloads addService().
Create a BrisaService and add it to the device. We recommend using this method for better object orientation.
See also:
BrisaUpnp::BrisaService
void BrisaDevice::addService (const QString & serviceType = "", const QString & serviceId = "", const QString & SCPDURL = "", const QString & controlURL = "", const QString & eventSubURL = "")
Creates and adds a service to the device with the given information.
void BrisaDevice::clear ()
Clears the device information, including services, icons and embedded devices.
void BrisaDevice::doByeBye ()
Sends the ssdp:byebye messages for root device, embedded devices and services according to the UPnP 1.0 especification.
Referenced by stop().
void BrisaDevice::doNotify ()
Sends the ssdp:alive messages for root device, embedded devices and services according to the UPnP 1.0 especification.
Referenced by start().
QString BrisaDevice::getAttribute (xmlTags key) const
Attribute getter.
See also:
setAttribute()
Referenced by BrisaDevice(), operator=(), and BrisaUpnp::BrisaDeviceXMLHandler::xmlGenerator().
QList< BrisaDevice * > BrisaDevice::getEmbeddedDeviceList () const
Returns the embedded device list.
See also:
getIconList() , getServiceList()
Referenced by operator=().
QList< BrisaIcon > BrisaDevice::getIconList () const
Returns the icon list.
See also:
getEmbeddedDeviceList() , getServiceList()
Referenced by operator=().
BrisaService * BrisaDevice::getServiceById (const QString & serviceId)
Getter for BrisaService in the service list.
BrisaService * BrisaDevice::getServiceByType (const QString & serviceType)
Getter for BrisaService in the service list.
QList< BrisaService * > BrisaDevice::getServiceList () const
Returns the service list.
See also:
getEmbeddedDeviceList() , getIconList()
Referenced by operator=().
BrisaDevice & BrisaDevice::operator= (const BrisaDevice & dev)
Assigns dev to this BrisaDevice and returns a copy.
void BrisaDevice::respondMSearch (const QString & st, const QString & senderIp, quint16 senderPort) [slot]
Slot connected to the msearchRequestReceived() signal comming from the ssdp module.
It parses the search type and responds accordingly.
See also:
respondMSearchAll()
Referenced by BrisaDevice().
void BrisaDevice::setAttribute (xmlTags key, const QString & value)
Attribute setter.
See also:
getAttribute()
void BrisaDevice::start ()
Call this method to join the network and start the device.
See also:
stop()
void BrisaDevice::stop ()
Stops the device and leaves the network.
See also:
start()
Referenced by ~BrisaDevice().
The documentation for this class was generated from the following files:
src/upnp/device/brisadevice.h
src/upnp/device/brisadevice.cpp