BRisa Qt: BrisaUpnp::BrisaStateVariable Class Reference
BrisaUpnp::BrisaStateVariable Class Reference
Represents the service's state variables.
#include <BrisaUpnp/BrisaStateVariable>
Public Types
enum BrisaStateVariableAttribute {
Name, SendEvents, DataType, DefaultValue,
AllowedValue, Minimum, Maximum, Step,
Value
}
Signals
void changed (BrisaStateVariable *)
Public Member Functions
BrisaStateVariable (QString sendEvents="", QString name="", QString datatype="", QString defaultValue="", QString maximum="", QString minimum="", QString step="", QObject *parent=0)
Constructs a BrisaStateVariable that sendEvents with the given name, datatype, defaultValue, maximum value, minimum value, value step, and parent.
BrisaStateVariable (const BrisaStateVariable &)
Constructs a BrisaStateVariable from the given variable.
BrisaStateVariable & operator= (const BrisaStateVariable &)
Sets this variable equals to variable.
void setAttribute (BrisaStateVariableAttribute attr, QVariant value)
Sets its attribute attr to the given value.
QString getAttribute (BrisaStateVariableAttribute attr, int index=0) const
Returns attr value as a QString.
QVariant getValue () const
Returns the stored value as a QVariant.
QVariant::Type getDataType () const
bool sendEvents () const
Returns true if the variable is set to send events.
void addAllowedValue (QString allowedValue)
Adds a value to the list of values that can be set to its Value attribute.
QList< QString > getAllowedValueList ()
Returns the list of values that can be set to its Value attribute.
void clear ()
Clears this variable's attributtes.
Detailed Description
Represents the service's state variables.
Member Enumeration Documentation
enum BrisaUpnp::BrisaStateVariable::BrisaStateVariableAttribute
Enumerator:
Name
SendEvents
DataType
DefaultValue
AllowedValue
Minimum
Maximum
Step
Value
Constructor & Destructor Documentation
BrisaStateVariable::BrisaStateVariable (QString sendEvents = "", QString name = "", QString datatype = "", QString defaultValue = "", QString maximum = "", QString minimum = "", QString step = "", QObject * parent = 0)
Constructs a BrisaStateVariable that sendEvents with the given name, datatype, defaultValue, maximum value, minimum value, value step, and parent.
BrisaStateVariable::BrisaStateVariable (const BrisaStateVariable & variable)
Constructs a BrisaStateVariable from the given variable.
Member Function Documentation
void BrisaStateVariable::addAllowedValue (QString allowedValue)
Adds a value to the list of values that can be set to its Value attribute.
Referenced by BrisaUpnp::BrisaServiceXMLHandler::characters().
void BrisaUpnp::BrisaStateVariable::changed (BrisaStateVariable *) [signal]
Referenced by setAttribute().
void BrisaStateVariable::clear ()
Clears this variable's attributtes.
QList< QString > BrisaStateVariable::getAllowedValueList ()
Returns the list of values that can be set to its Value attribute.
QString BrisaStateVariable::getAttribute (BrisaStateVariableAttribute attr, int index = 0) const
Returns attr value as a QString.
Referenced by BrisaStateVariable(), and operator=().
QVariant::Type BrisaStateVariable::getDataType () const
QVariant BrisaStateVariable::getValue () const
Returns the stored value as a QVariant.
Referenced by BrisaStateVariable(), and operator=().
BrisaStateVariable & BrisaStateVariable::operator= (const BrisaStateVariable & variable)
Sets this variable equals to variable.
bool BrisaStateVariable::sendEvents () const
Returns true if the variable is set to send events.
Referenced by BrisaStateVariable(), and operator=().
void BrisaStateVariable::setAttribute (BrisaStateVariableAttribute attr, QVariant value)
Sets its attribute attr to the given value.
Referenced by BrisaUpnp::BrisaServiceXMLHandler::characters(), and BrisaUpnp::BrisaServiceXMLHandler::startElement().
The documentation for this class was generated from the following files:
src/upnp/brisastatevariable.h
src/upnp/brisastatevariable.cpp