BRisa Qt: BrisaCore::BrisaWebServiceProvider Class Reference
BrisaCore::BrisaWebServiceProvider Class Reference
The BrisaWebServiceProvider class works as web service manager for the web server.
#include <brisawebserver.h>
Public Member Functions
BrisaWebServiceProvider (QxtAbstractWebSessionManager *sm, QObject *parent)
Constructor for BrisaWebServiceProvider.
~BrisaWebServiceProvider ()
Destructor for BrisaWebServiceProvider.
void addFile (const QString path, QString filePath)
Call this method to add a BrisaWebFile to the web service.
void addContent (const QString path, QString content)
Call this method to add a BrisaWebStaticContent to the web service.
void pageRequestedEvent (QxtWebRequestEvent *event)
Reimplemented from libQxt.
Protected Member Functions
void indexRequested (QxtWebRequestEvent *event)
Reimplemented from libQxt.
Detailed Description
The BrisaWebServiceProvider class works as web service manager for the web server.
The BrisaWebServiceProvider has convenience methods for managing web services, like addFile() and addContent(). It also keeps track of all files and content stored into the web service.
Constructor & Destructor Documentation
BrisaCore::BrisaWebServiceProvider::BrisaWebServiceProvider (QxtAbstractWebSessionManager * sm, QObject * parent) [inline]
Constructor for BrisaWebServiceProvider.
Parameters:
sm empty
parent empty
BrisaCore::BrisaWebServiceProvider::~BrisaWebServiceProvider () [inline]
Destructor for BrisaWebServiceProvider.
Member Function Documentation
void BrisaWebServiceProvider::addContent (const QString path, QString content)
Call this method to add a BrisaWebStaticContent to the web service.
Parameters:
path empty
content empty
void BrisaWebServiceProvider::addFile (const QString path, QString filePath)
Call this method to add a BrisaWebFile to the web service.
Parameters:
path empty
filePath empty
Referenced by BrisaUpnp::BrisaService::buildWebServiceTree(), and BrisaCore::BrisaWebserver::publishFile().
void BrisaCore::BrisaWebServiceProvider::indexRequested (QxtWebRequestEvent * event) [inline, protected]
Reimplemented from libQxt.
This method calls the BrisaWebStaticContent index() method.
Parameters:
event empty
Referenced by pageRequestedEvent().
void BrisaWebServiceProvider::pageRequestedEvent (QxtWebRequestEvent * event)
Reimplemented from libQxt.
The documentation for this class was generated from the following files:
src/core/brisawebserver.h
src/core/brisawebserver.cpp