BRisa Qt: BrisaUpnp::BrisaServiceParserContext Class Reference
BrisaUpnp::BrisaServiceParserContext Class Reference
#include <brisaservicexmlhandler.h>
Public Member Functions
BrisaServiceParserContext (BrisaServiceParserContext *parent=0, BrisaAbstractService *target=0)
BrisaAction * getAction (void)
BrisaAbstractService * getService (void)
BrisaStateVariable * getStateVariable (void)
BrisaArgument * getArgument (void)
void setAction (BrisaAction *action)
void setService (BrisaAbstractService *service)
void setStateVariable (BrisaStateVariable *stateVariable)
void setArgument (BrisaArgument *argument)
bool hasParent (void)
BrisaServiceParserContext * getParent (void)
Public Attributes
int stateSkip
saxParserState state
Constructor & Destructor Documentation
BrisaUpnp::BrisaServiceParserContext::BrisaServiceParserContext (BrisaServiceParserContext * parent = 0, BrisaAbstractService * target = 0) [inline]
Member Function Documentation
BrisaAction* BrisaUpnp::BrisaServiceParserContext::getAction (void) [inline]
Referenced by BrisaUpnp::BrisaServiceXMLHandler::characters(), BrisaUpnp::BrisaServiceXMLHandler::endElement(), and BrisaUpnp::BrisaServiceXMLHandler::startElement().
BrisaArgument* BrisaUpnp::BrisaServiceParserContext::getArgument (void) [inline]
Referenced by BrisaUpnp::BrisaServiceXMLHandler::characters(), BrisaUpnp::BrisaServiceXMLHandler::endElement(), and BrisaUpnp::BrisaServiceXMLHandler::startElement().
BrisaServiceParserContext* BrisaUpnp::BrisaServiceParserContext::getParent (void) [inline]
BrisaAbstractService* BrisaUpnp::BrisaServiceParserContext::getService (void) [inline]
Referenced by BrisaUpnp::BrisaServiceXMLHandler::characters(), and BrisaUpnp::BrisaServiceXMLHandler::endElement().
BrisaStateVariable* BrisaUpnp::BrisaServiceParserContext::getStateVariable (void) [inline]
Referenced by BrisaUpnp::BrisaServiceXMLHandler::characters(), BrisaUpnp::BrisaServiceXMLHandler::endElement(), and BrisaUpnp::BrisaServiceXMLHandler::startElement().
bool BrisaUpnp::BrisaServiceParserContext::hasParent (void) [inline]
void BrisaUpnp::BrisaServiceParserContext::setAction (BrisaAction * action) [inline]
Referenced by BrisaUpnp::BrisaServiceXMLHandler::endElement(), and BrisaUpnp::BrisaServiceXMLHandler::startElement().
void BrisaUpnp::BrisaServiceParserContext::setArgument (BrisaArgument * argument) [inline]
Referenced by BrisaUpnp::BrisaServiceXMLHandler::endElement(), and BrisaUpnp::BrisaServiceXMLHandler::startElement().
void BrisaUpnp::BrisaServiceParserContext::setService (BrisaAbstractService * service) [inline]
void BrisaUpnp::BrisaServiceParserContext::setStateVariable (BrisaStateVariable * stateVariable) [inline]
Referenced by BrisaUpnp::BrisaServiceXMLHandler::endElement(), and BrisaUpnp::BrisaServiceXMLHandler::startElement().
Member Data Documentation
saxParserState BrisaUpnp::BrisaServiceParserContext::state
Referenced by BrisaUpnp::BrisaServiceXMLHandler::characters(), BrisaUpnp::BrisaServiceXMLHandler::endElement(), BrisaUpnp::BrisaServiceXMLHandler::parseService(), and BrisaUpnp::BrisaServiceXMLHandler::startElement().
int BrisaUpnp::BrisaServiceParserContext::stateSkip
Referenced by BrisaUpnp::BrisaServiceXMLHandler::endElement(), BrisaUpnp::BrisaServiceXMLHandler::parseService(), and BrisaUpnp::BrisaServiceXMLHandler::startElement().
The documentation for this class was generated from the following file:
src/upnp/brisaservicexmlhandler.h