BRisa Qt: BrisaCore::BrisaWebService Class Reference
BrisaCore::BrisaWebService Class Reference
Web service abstraction class.
#include <brisawebserver.h>
Public Slots
void pageRequestedEvent (QxtWebRequestEvent *event)
This method receives all web service requests and emits a genericRequestReceived() signal.
void respond (QByteArray response)
Responds response to the session and request ID currently stored in BrisaWebService, if using this method the response must be synchronous because the request and session ID can change quickly.
void respond (const QByteArray &response, const int &sessionId, const int &requestId)
Reimplements respond().
void respond (const QHttpResponseHeader &response)
Reimplements respond() This method responds only a HTTP header to the session and request ID stored in BrisaWebService.
void respond (const QHttpResponseHeader &response, const int &sessionId, const int &requestId)
Reimplements respond().
Signals
void genericRequestReceived (const QString &method, const QMultiHash< QString, QString > &headers, const QByteArray &requestContent, int sessionId, int requestId)
This signal is emmited when BrisaWebService receives a request.
void genericRequestReceived (BrisaWebService *service, QMultiHash< QString, QString >, QString requestContent)
Reimplements genericRequestReceived() This signal is emmited when BrisaWebService receives a request, the main difference is that this signal has a pointer to the class that is emmiting the signal.
Public Member Functions
BrisaWebService (QxtAbstractWebSessionManager *sm, QObject *parent=0)
Constructor for BrisaWebService.
~BrisaWebService ()
Destructor for BrisaWebService.
Detailed Description
Web service abstraction class.
BrisaWebService is used to receive and respond UPnP action and event requests. Currently this class is used mostly with BrisaService and BrisaEventController.
See also:
BrisaUpnp::BrisaService , BrisaUpnp::BrisaEventController
Constructor & Destructor Documentation
BrisaCore::BrisaWebService::BrisaWebService (QxtAbstractWebSessionManager * sm, QObject * parent = 0) [inline]
Constructor for BrisaWebService.
Parameters:
sm Session manager
parent parent
BrisaCore::BrisaWebService::~BrisaWebService () [inline]
Destructor for BrisaWebService.
Member Function Documentation
void BrisaCore::BrisaWebService::genericRequestReceived (BrisaWebService * service, QMultiHash< QString, QString > , QString requestContent) [signal]
Reimplements genericRequestReceived() This signal is emmited when BrisaWebService receives a request, the main difference is that this signal has a pointer to the class that is emmiting the signal.
Parameters:
service empty
? ?
requestContent empty
void BrisaCore::BrisaWebService::genericRequestReceived (const QString & method, const QMultiHash< QString, QString > & headers, const QByteArray & requestContent, int sessionId, int requestId) [signal]
This signal is emmited when BrisaWebService receives a request.
Parameters:
method empty
headers empty
requestContent empty
sessionId empty
requestId empty
Referenced by BrisaUpnp::BrisaEventController::BrisaEventController().
void BrisaCore::BrisaWebService::pageRequestedEvent (QxtWebRequestEvent * event) [inline, slot]
This method receives all web service requests and emits a genericRequestReceived() signal.
If the request method is of "POST" type, the web service will reply a default message.
Note: Reimplemented from libQxt.
Parameters:
event empty
void BrisaCore::BrisaWebService::respond (const QHttpResponseHeader & response, const int & sessionId, const int & requestId) [inline, slot]
Reimplements respond().
This method responds only a HTTP header using the given session and request ID.
Parameters:
response empty
sessionId empty
requestId empty
void BrisaCore::BrisaWebService::respond (const QHttpResponseHeader & response) [inline, slot]
Reimplements respond() This method responds only a HTTP header to the session and request ID stored in BrisaWebService.
Parameters:
response empty
void BrisaCore::BrisaWebService::respond (const QByteArray & response, const int & sessionId, const int & requestId) [inline, slot]
Reimplements respond().
We recommend using this method given the fact that it supports asynchronous requests.
Parameters:
response empty
sessionId empty
requestId empty
void BrisaCore::BrisaWebService::respond (QByteArray response) [inline, slot]
Responds response to the session and request ID currently stored in BrisaWebService, if using this method the response must be synchronous because the request and session ID can change quickly.
Parameters:
response empty
Referenced by BrisaUpnp::BrisaEventController::subscribe(), and BrisaUpnp::BrisaEventController::unsubscribe().
The documentation for this class was generated from the following file:
src/core/brisawebserver.h