BRisa Qt: BrisaUpnp::BrisaDeviceParserContext Class Reference
BrisaUpnp::BrisaDeviceParserContext Class Reference
#include <brisadevicexmlhandlercp.h>
Public Member Functions
BrisaDeviceParserContext (BrisaDeviceParserContext *parent=0, BrisaControlPointDevice *target=0)
BrisaIcon * getIcon (void)
BrisaControlPointDevice * getDevice (void)
BrisaControlPointService * getService (void)
void setIcon (BrisaIcon *icon)
void setDevice (BrisaControlPointDevice *device)
void setService (BrisaControlPointService *service)
bool hasParent (void)
BrisaDeviceParserContext * getParent (void)
Public Attributes
int stateSkip
SaxParserState state
Constructor & Destructor Documentation
BrisaUpnp::BrisaDeviceParserContext::BrisaDeviceParserContext (BrisaDeviceParserContext * parent = 0, BrisaControlPointDevice * target = 0) [inline]
Member Function Documentation
BrisaControlPointDevice* BrisaUpnp::BrisaDeviceParserContext::getDevice (void) [inline]
Referenced by BrisaUpnp::BrisaDeviceXMLHandlerCP::characters(), BrisaUpnp::BrisaDeviceXMLHandlerCP::endElement(), and BrisaUpnp::BrisaDeviceXMLHandlerCP::startElement().
BrisaIcon* BrisaUpnp::BrisaDeviceParserContext::getIcon (void) [inline]
Referenced by BrisaUpnp::BrisaDeviceXMLHandlerCP::characters(), BrisaUpnp::BrisaDeviceXMLHandlerCP::endElement(), and BrisaUpnp::BrisaDeviceXMLHandlerCP::startElement().
BrisaDeviceParserContext* BrisaUpnp::BrisaDeviceParserContext::getParent (void) [inline]
Referenced by BrisaUpnp::BrisaDeviceXMLHandlerCP::endElement().
BrisaControlPointService* BrisaUpnp::BrisaDeviceParserContext::getService (void) [inline]
Referenced by BrisaUpnp::BrisaDeviceXMLHandlerCP::characters(), BrisaUpnp::BrisaDeviceXMLHandlerCP::endElement(), and BrisaUpnp::BrisaDeviceXMLHandlerCP::startElement().
bool BrisaUpnp::BrisaDeviceParserContext::hasParent (void) [inline]
Referenced by BrisaUpnp::BrisaDeviceXMLHandlerCP::endElement().
void BrisaUpnp::BrisaDeviceParserContext::setDevice (BrisaControlPointDevice * device) [inline]
Referenced by BrisaUpnp::BrisaDeviceXMLHandlerCP::startElement().
void BrisaUpnp::BrisaDeviceParserContext::setIcon (BrisaIcon * icon) [inline]
Referenced by BrisaUpnp::BrisaDeviceXMLHandlerCP::endElement(), and BrisaUpnp::BrisaDeviceXMLHandlerCP::startElement().
void BrisaUpnp::BrisaDeviceParserContext::setService (BrisaControlPointService * service) [inline]
Referenced by BrisaUpnp::BrisaDeviceXMLHandlerCP::endElement(), and BrisaUpnp::BrisaDeviceXMLHandlerCP::startElement().
Member Data Documentation
SaxParserState BrisaUpnp::BrisaDeviceParserContext::state
Referenced by BrisaUpnp::BrisaDeviceXMLHandlerCP::characters(), BrisaUpnp::BrisaDeviceXMLHandlerCP::endElement(), BrisaUpnp::BrisaDeviceXMLHandlerCP::parseDevice(), and BrisaUpnp::BrisaDeviceXMLHandlerCP::startElement().
int BrisaUpnp::BrisaDeviceParserContext::stateSkip
Referenced by BrisaUpnp::BrisaDeviceXMLHandlerCP::endElement(), BrisaUpnp::BrisaDeviceXMLHandlerCP::parseDevice(), and BrisaUpnp::BrisaDeviceXMLHandlerCP::startElement().
The documentation for this class was generated from the following file:
src/upnp/controlpoint/brisadevicexmlhandlercp.h