BRisa Qt: BrisaUpnp::BrisaMSearchClientCP Class Reference
BrisaUpnp::BrisaMSearchClientCP Class Reference
SSDP MSearch implementation for UPnP control points.
#include <BrisaUpnp/BrisaMSearchClientCP>
Public Slots
void discover ()
Signals
void msearchResponseReceived (const QString &usn, const QString &location, const QString &st, const QString &ext, const QString &server, const QString &cacheControl)
Public Member Functions
BrisaMSearchClientCP (QObject *parent=0, const QString &type=DEFAULT_SEARCH_TYPE, int mx=5)
virtual ~BrisaMSearchClientCP ()
void doubleDiscover ()
bool isRunning () const
void start (int interval=DEFAULT_SEARCH_TIME)
void stop ()
Detailed Description
SSDP MSearch implementation for UPnP control points.
Create a new BrisaMSearchClientCP with the desired service type and mx values, and call start() to begin sending discovery messages to possible devices in the multicast group. When a device responds to a msearch request, msearchResponseReceived() signal is emmited.
Constructor & Destructor Documentation
BrisaMSearchClientCP::BrisaMSearchClientCP (QObject * parent = 0, const QString & type = DEFAULT_SEARCH_TYPE, int mx = 5)
BrisaMSearchClientCP::~BrisaMSearchClientCP () [virtual]
Member Function Documentation
void BrisaMSearchClientCP::discover () [slot]
Referenced by BrisaMSearchClientCP(), BrisaUpnp::BrisaControlPoint::discover(), and doubleDiscover().
void BrisaMSearchClientCP::doubleDiscover ()
bool BrisaMSearchClientCP::isRunning () const
Referenced by start(), stop(), and ~BrisaMSearchClientCP().
void BrisaUpnp::BrisaMSearchClientCP::msearchResponseReceived (const QString & usn, const QString & location, const QString & st, const QString & ext, const QString & server, const QString & cacheControl) [signal]
void BrisaMSearchClientCP::start (int interval = DEFAULT_SEARCH_TIME)
Referenced by BrisaUpnp::BrisaControlPoint::start().
void BrisaMSearchClientCP::stop ()
Referenced by BrisaUpnp::BrisaControlPoint::stop(), and ~BrisaMSearchClientCP().
The documentation for this class was generated from the following files:
src/upnp/controlpoint/brisamsearchclientcp.h
src/upnp/controlpoint/brisamsearchclientcp.cpp