BRisa Qt: BrisaUpnp::BrisaEventController Class Reference
BrisaUpnp::BrisaEventController Class Reference
#include <brisaeventcontroller.h>
Public Slots
void variableChanged (BrisaStateVariable *variable)
Slot that shall be called when some service's state variable change.
void subscribe (const QMultiHash< QString, QString > &subscriberInfo, int sessionId, int requestId)
Creates a subscription for the given subscriberInfo, sessionId and requestId.
void unsubscribe (const QMultiHash< QString, QString > &subscriberInfo, int sessionId, int requestId)
Removes the subscription for the given subscriberInfo, sessionId and requestId.
void parseGenericRequest (const QString &method, const QMultiHash< QString, QString > &headers, const QByteArray &requestContent, int sessionId, int requestId)
Parses a generic request to web service and calls the local related methods as necessary.
Public Member Functions
BrisaEventController (QxtAbstractWebSessionManager *sessionManager, QList< BrisaStateVariable * > *stateVariableList, QObject *parent=0)
~BrisaEventController ()
Destructor.
Constructor & Destructor Documentation
BrisaEventController::BrisaEventController (QxtAbstractWebSessionManager * sessionManager, QList< BrisaStateVariable * > * stateVariableList, QObject * parent = 0)
BrisaEventController::~BrisaEventController ()
Destructor.
Member Function Documentation
void BrisaEventController::parseGenericRequest (const QString & method, const QMultiHash< QString, QString > & headers, const QByteArray & requestContent, int sessionId, int requestId) [slot]
Parses a generic request to web service and calls the local related methods as necessary.
Referenced by BrisaEventController().
void BrisaEventController::subscribe (const QMultiHash< QString, QString > & subscriberInfo, int sessionId, int requestId) [slot]
Creates a subscription for the given subscriberInfo, sessionId and requestId.
Referenced by parseGenericRequest().
void BrisaEventController::unsubscribe (const QMultiHash< QString, QString > & subscriberInfo, int sessionId, int requestId) [slot]
Removes the subscription for the given subscriberInfo, sessionId and requestId.
Referenced by parseGenericRequest().
void BrisaEventController::variableChanged (BrisaStateVariable * variable) [slot]
Slot that shall be called when some service's state variable change.
The documentation for this class was generated from the following files:
src/upnp/device/brisaeventcontroller.h
src/upnp/device/brisaeventcontroller.cpp